added Articulated soft robot loader and description
Gepetto/example-robot-data pull request #115
Opened 2021-12-08 06:55 UTC by spykspeigel

2021-12-08 07:12 UTC, jcarpent requested changes
Thanks @spykspeigel for sharing this model.
Before merging this PR, it is important for us to understand:
- where does this model come from? Can it be provided by anybody?
- does this model will be useful to the whole community of Pinocchio, Crocoddyl and other software users?

By the way, you should only provide the minimal set of files to make things loadable by the parsers. At the time being, there are a lot of files that are not required (CMake files for instance).

2021-12-08 08:35 UTC, cmastalli commented
> Thanks @spykspeigel for sharing this model.
> Before merging this PR, it is important for us to understand:
> - where does this model come from? Can it be provided by anybody?
> - does this model will be useful to the whole community of Pinocchio, Crocoddyl and other software users?
> 
> By the way, you should only provide the minimal set of files to make things loadable by the parsers. At the time being, there are a lot of files that are not required (CMake files for instance).

@spykspeigel is working with me. This robot will eventually be useful for Crocoddyl, when we finished our ongoing work.

The robot is originally defined by Pisa. I guess we are authorized to publish this data, right @spykspeigel ?

Furthermore, as pointed out by @jcarpent, we really need the smallest set of files, which are the urdf and dae files.

You need to remove the xacro, launch, STL files.

2021-12-09 08:45 UTC, nim65s requested changes
In addition to other comments, and the details about the load function, could you add a README documenting the robot provenance and its origin license ?

2021-12-09 08:45 UTC, nim65s commented on python/example_robot_data/__init__.py
> +                            loadTalosLegs, loadTiago, loadTiagoNoHand, loadUR, readParamsFromSrdf, loadAsrTwoDof)
You can remove this

2021-12-09 08:45 UTC, nim65s commented on python/example_robot_data/robots_loader.py
> +def loadAsrTwoDof():
There is no need to create a deprecated function. The Loader class is enough

2021-12-11 07:33 UTC, spykspeigel commented
Dear All, Thanks for the comments. I have made the suggested changes i.e. removed the unnecessary files, added readme and license files. Kindly let me know if it needs any further changes.

2021-12-11 09:41 UTC, nim65s requested changes
Thanks for the fixes, it's cleaner now !

I still see 2 issues:
1. the CI is failing. This is because you added the robot under the name `asr_twodof`, and tried to uni-test the robot `asr_two_dof`. Please pick one :)
2. you are also adding `simplecube_description`. If this not intended, you should remove this folder. Otherwise, you should add a loader and a unit test for this robot too. And maybe update the title of this pull request

2021-12-13 12:16 UTC, cmastalli requested changes
Please also handle the issue about the `simplecube` raised by @nim65s in https://github.com/Gepetto/example-robot-data/pull/115#pullrequestreview-829517409

2021-12-13 12:16 UTC, cmastalli commented on robots/asr_twodof_description/urdf/TwoDofs.urdf
> +    </gazebo>
I think we should remove these plugins as they are not standard ones.
@nim65s  and @jcarpent - do you agree or not on this topic?

2021-12-13 12:16 UTC, cmastalli commented on robots/simplecube_description/urdf/simplecube.urdf
> +    </gazebo>
same here

2021-12-13 13:10 UTC, spykspeigel commented
@nim65s the urdf file in `two_dof_description` depends on the dae files from `simplecube_description`. So I have moved the corresponding files in folder `qb_meshes` to the `two_dof_description` and removed `simplecube_description` .

2021-12-22 10:44 UTC, cmastalli approved these changes

2022-02-18 10:43 UTC, nim65s approved these changes

2022-02-18 10:45 UTC, merged